### ISSUE TITLE
AbilityElementResistancesParser: Unknown parameters

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#158]
See 913253

**Comment by Wisdomb33r** [comment]
The 9-th parameter of this skill, which is almost always 1, is in this case 3.
Dark Bloom (215680) has a value of 0 for this parameter and is one of the very few with a value other than 1.
Neither aEnigma DM nor wiki parsing is using this parameter. With 3 different values, it must have a meaning, but it is currently unknown.
