### ISSUE TITLE
Change parsing of random skills

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#308]
Up to now random skills were considered as activated skills.
The console should rather parse them as it does for the delayed skills, with a single skill for the whole action.

See for instance Awakened Dragon Akstar:

- [ ] 236574 Lame destructrice - Fissure glaciale

**Comment by Sylvie** [comment]
@Wisdomb33r Est-ce qu'on laisse tomber ce ticket? Ça risque de créer plus d'ennuis que ce que ça peut résoudre.

**Comment by Wisdomb33r** [comment]
Oui, déjà les switch skills c'était peut-être pas une bonne idée de changer le wording car ça fait des trucs bizarres (genre un passif qui augmente la puissance de la version améliorée du switch skill qui a un autre nom que le skill de base... du coup impossible de faire le lien entre l'effet du passif et le sort amélioré). Je ferme.
