### ISSUE TITLE
Skill shown as different from DB after re-pushing it

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#345]
See **Je ne mourrai jamais !**

- [x] 702750
- [x] 702760

The curious thing is that the base ability is not affected : 204960

**Comment by Sylvie** [comment]
See also:
229984 On n'aura pas ma peau 
This ability is a counter-attack whose parsing was changed to use an activated skill. It seems the frames are not removed from the stored skill, thus the apparent difference with the parsed skill.

**Comment by Wisdomb33r** [comment]
See also 910909
