### ISSUE TITLE
Wrong frames parsing on NV Sol LB

### ISSUE THREAD

**Issue by Wisdomb33r** [Wisdomb33r/ffch-admin#359]
- [x] NV Sol (normal form) is parsed with 1 hit (frame 11), but should be parsed as 24 hits.

**Comment by Sylvie** [comment]
Ignacio has the same issue

**Comment by Wisdomb33r** [comment]
- [ ] Edward & Alphonse (normal form)
- [ ] Rain & Fina (normal form)
