### ISSUE TITLE
Broken screen for items with several recipes

### ISSUE THREAD

**Issue by Wisdomb33r** [Wisdomb33r/ffch-admin#489]
When an item has several way of crafting it (several recipes), the recipe screen is broken as soon as you push the second recipe :

- `Storage exception : several recettes found with recette gumi ID: ? and resultat gumi ID1100000507`

Example : Celestite Crown of Will

**Comment by Sylvie** [comment]
See the call to `is_null()` in recettes.php on lines 126 and 133.

**Comment by Sylvie** [comment]
See also the mess on line 96
