### ISSUE TITLE
Power increases for cool-down abilities

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#51]
Abilities providing a power increase for an ability on cool-down target the activated ability. However we store the activating ability in the DB.
We must either find a way to store the correct link in the power increase effect or make link pointing to the activated ability redirect to the activating ability.

**Comment by Wisdomb33r** [comment]
Skill switches have similar issue (but not for the enhanced skill, only the base one).

**Comment by Wisdomb33r** [comment]
Fixed in 6.0.0 RC1.
