### ISSUE TITLE
Ability requirements

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#69]
Add an automatic parsing of requirements (sex, unit, ...) to abilities.

**Comment by Sylvie** [comment]
Skills to be checked:
- 910388
- 211490

**Comment by Sylvie** [comment]
Some abilities also require to finish a quest:

- [ ] 40140 
- [ ] 40130 
- [ ] 40160
- [ ] 40170
- [ ] 40190
- [ ] 40200
- [ ] 40210
- [ ] 40220

**Comment by Wisdomb33r** [comment]
I guess we cannot parse Kimahri requirements. `[["SWITCH",  18519013]]` does not seam to be parseable. The number might refer to player-specific internal value (indicating this player has done this quest... or something like that).
So these SWITCH requirements will be ... won't fix I guess.

**Comment by Sylvie** [comment]
> I guess we cannot parse Kimahri requirements. 

I guess we can, there are occurrences of this ID in missions.json

```` Bestiole@Chogall MINGW64 ~/Documents/Brave Exvius/9. JSON data (master)
$ grep  -r "18519013" .
./missions.json:                "reward": ["SWITCH", 18519013, 1]
./missions.json:                "reward": ["SWITCH", 18519013, 1]
./skills_magic.json:        "requirements": [["SWITCH",  18519013]]
./skills_magic.json:        "requirements": [["SWITCH",  18519013]]
